/**
 * LandingFooter (FD-1d) — extracted from Landing.tsx and REGRADED to match the
 * Bloomberg header family: panel base + hairline border (was brand-purple-deep
 * in FD-1c), mono micro-labels, token-native, zero hex. Shared by the Landing
 * and every /modules page.
 *
 * Carries the CPA disclaimer (copy verbatim from page.tsx :202-207) — legal
 * boilerplate that belongs on every marketing surface, including the Tax
 * module page. Legal links + Pricing carry over.
 */

import Link from 'next/link';

export default function LandingFooter() {
  return (
    <footer className="border-t border-panel-border bg-panel text-white">
      <div className="max-w-3xl mx-auto px-4 lg:px-8 pt-8 text-center">
        <p className="text-xs text-white/50 leading-relaxed">
          Temple Stuart is not a CPA firm, tax preparer, or licensed financial advisor.
          All tax figures generated by this platform are estimates for informational purposes only
          and must be verified by a qualified tax professional before filing.
          Use of this software does not constitute tax advice.
        </p>
      </div>
      <div className="max-w-7xl mx-auto px-4 lg:px-8 py-8">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-white flex items-center justify-center">
              <span className="text-brand-purple font-bold text-sm">TS</span>
            </div>
            <div className="font-mono text-[10px] uppercase tracking-wider text-white/50">© 2026 Temple Stuart, LLC</div>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/how-pricing-works" className="text-xs text-white/50 hover:text-white/80">Pricing</Link>
            <a href="/terms" className="text-xs text-white/50 hover:text-white/80">Terms of Service</a>
            <a href="/privacy" className="text-xs text-white/50 hover:text-white/80">Privacy Policy</a>
          </div>
        </div>
      </div>
    </footer>
  );
}
