export const JURISDICTIONS = [
  { code: 'US-federal', label: 'US Federal' },
  { code: 'US-AL', label: 'Alabama' },
  { code: 'US-AK', label: 'Alaska' },
  { code: 'US-AZ', label: 'Arizona' },
  { code: 'US-AR', label: 'Arkansas' },
  { code: 'US-CA', label: 'California' },
  { code: 'US-CO', label: 'Colorado' },
  { code: 'US-CT', label: 'Connecticut' },
  { code: 'US-DE', label: 'Delaware' },
  { code: 'US-DC', label: 'Washington DC' },
  { code: 'US-FL', label: 'Florida' },
  { code: 'US-GA', label: 'Georgia' },
  { code: 'US-HI', label: 'Hawaii' },
  { code: 'US-ID', label: 'Idaho' },
  { code: 'US-IL', label: 'Illinois' },
  { code: 'US-IN', label: 'Indiana' },
  { code: 'US-IA', label: 'Iowa' },
  { code: 'US-KS', label: 'Kansas' },
  { code: 'US-KY', label: 'Kentucky' },
  { code: 'US-LA', label: 'Louisiana' },
  { code: 'US-ME', label: 'Maine' },
  { code: 'US-MD', label: 'Maryland' },
  { code: 'US-MA', label: 'Massachusetts' },
  { code: 'US-MI', label: 'Michigan' },
  { code: 'US-MN', label: 'Minnesota' },
  { code: 'US-MS', label: 'Mississippi' },
  { code: 'US-MO', label: 'Missouri' },
  { code: 'US-MT', label: 'Montana' },
  { code: 'US-NE', label: 'Nebraska' },
  { code: 'US-NV', label: 'Nevada' },
  { code: 'US-NH', label: 'New Hampshire' },
  { code: 'US-NJ', label: 'New Jersey' },
  { code: 'US-NM', label: 'New Mexico' },
  { code: 'US-NY', label: 'New York' },
  { code: 'US-NC', label: 'North Carolina' },
  { code: 'US-ND', label: 'North Dakota' },
  { code: 'US-OH', label: 'Ohio' },
  { code: 'US-OK', label: 'Oklahoma' },
  { code: 'US-OR', label: 'Oregon' },
  { code: 'US-PA', label: 'Pennsylvania' },
  { code: 'US-RI', label: 'Rhode Island' },
  { code: 'US-SC', label: 'South Carolina' },
  { code: 'US-SD', label: 'South Dakota' },
  { code: 'US-TN', label: 'Tennessee' },
  { code: 'US-TX', label: 'Texas' },
  { code: 'US-UT', label: 'Utah' },
  { code: 'US-VT', label: 'Vermont' },
  { code: 'US-VA', label: 'Virginia' },
  { code: 'US-WA', label: 'Washington' },
  { code: 'US-WV', label: 'West Virginia' },
  { code: 'US-WI', label: 'Wisconsin' },
  { code: 'US-WY', label: 'Wyoming' },
  { code: 'EU', label: 'European Union' },
  { code: 'UK', label: 'United Kingdom' },
  { code: 'International', label: 'International' },
] as const;

export type JurisdictionCode = (typeof JURISDICTIONS)[number]['code'];

export const JURISDICTION_LABEL: Record<string, string> = Object.fromEntries(
  JURISDICTIONS.map((j) => [j.code, j.label]),
);
