import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // ═══════════════════════════════════════════════════════════════════
  // FESTIVAL DESTINATIONS - 33 Major Festivals in Nomad-Friendly Places
  // ═══════════════════════════════════════════════════════════════════
  const festivalDestinations = [
    { festivalName: 'Envision Festival', city: 'Uvita', country: 'Costa Rica', genre: 'multi-genre', typicalMonth: 'February', durationDays: 4, ticketCost: 400, attendeeCount: 8000, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'SJO', visaEase: 'visa-free 90d' },
    { festivalName: 'Wonderfruit', city: 'Pattaya', country: 'Thailand', genre: 'multi-genre', typicalMonth: 'December', durationDays: 4, ticketCost: 250, attendeeCount: 20000, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'BKK', visaEase: 'visa-free 60d' },
    { festivalName: 'Epizode', city: 'Phu Quoc', country: 'Vietnam', genre: 'electronic', typicalMonth: 'December', durationDays: 11, ticketCost: 300, attendeeCount: 10000, monthlyRent: 400, costIndex: 9, nomadScore: 7, nearestAirport: 'PQC', visaEase: 'visa-free 15d' },
    { festivalName: 'Tribal Gathering', city: 'Playa Chiquita', country: 'Panama', genre: 'multi-genre', typicalMonth: 'March', durationDays: 7, ticketCost: 350, attendeeCount: 5000, monthlyRent: 700, costIndex: 8, nomadScore: 7, nearestAirport: 'PTY', visaEase: 'visa-free 180d' },
    { festivalName: 'NOS Alive', city: 'Lisbon', country: 'Portugal', genre: 'rock', typicalMonth: 'July', durationDays: 3, ticketCost: 180, attendeeCount: 60000, monthlyRent: 1200, costIndex: 6, nomadScore: 10, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { festivalName: 'Primavera Sound', city: 'Barcelona', country: 'Spain', genre: 'multi-genre', typicalMonth: 'June', durationDays: 4, ticketCost: 250, attendeeCount: 200000, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { festivalName: 'Ultra Europe', city: 'Split', country: 'Croatia', genre: 'electronic', typicalMonth: 'July', durationDays: 3, ticketCost: 200, attendeeCount: 150000, monthlyRent: 900, costIndex: 7, nomadScore: 7, nearestAirport: 'SPU', visaEase: 'Schengen 90d' },
    { festivalName: 'Sonar', city: 'Barcelona', country: 'Spain', genre: 'electronic', typicalMonth: 'June', durationDays: 3, ticketCost: 200, attendeeCount: 126000, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { festivalName: 'Lollapalooza Chile', city: 'Santiago', country: 'Chile', genre: 'multi-genre', typicalMonth: 'March', durationDays: 3, ticketCost: 200, attendeeCount: 180000, monthlyRent: 700, costIndex: 7, nomadScore: 7, nearestAirport: 'SCL', visaEase: 'visa-free 90d' },
    { festivalName: 'Lollapalooza Argentina', city: 'Buenos Aires', country: 'Argentina', genre: 'multi-genre', typicalMonth: 'March', durationDays: 3, ticketCost: 150, attendeeCount: 300000, monthlyRent: 600, costIndex: 8, nomadScore: 8, nearestAirport: 'EZE', visaEase: 'visa-free 90d' },
    { festivalName: 'Lollapalooza Brasil', city: 'Sao Paulo', country: 'Brazil', genre: 'multi-genre', typicalMonth: 'March', durationDays: 3, ticketCost: 200, attendeeCount: 250000, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'GRU', visaEase: 'visa-free 90d' },
    { festivalName: 'Stereo Picnic', city: 'Bogota', country: 'Colombia', genre: 'multi-genre', typicalMonth: 'March', durationDays: 4, ticketCost: 150, attendeeCount: 90000, monthlyRent: 600, costIndex: 8, nomadScore: 7, nearestAirport: 'BOG', visaEase: 'visa-free 90d' },
    { festivalName: 'Corona Capital', city: 'Mexico City', country: 'Mexico', genre: 'rock', typicalMonth: 'November', durationDays: 2, ticketCost: 150, attendeeCount: 180000, monthlyRent: 900, costIndex: 7, nomadScore: 10, nearestAirport: 'MEX', visaEase: 'visa-free 180d' },
    { festivalName: 'Burning Man', city: 'Black Rock', country: 'USA', genre: 'multi-genre', typicalMonth: 'August', durationDays: 8, ticketCost: 575, attendeeCount: 80000, monthlyRent: 2000, costIndex: 3, nomadScore: 8, nearestAirport: 'RNO', visaEase: 'ESTA/visa' },
    { festivalName: 'AfrikaBurn', city: 'Tankwa Karoo', country: 'South Africa', genre: 'multi-genre', typicalMonth: 'April', durationDays: 7, ticketCost: 150, attendeeCount: 13000, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'CPT', visaEase: 'visa-free 90d' },
    { festivalName: 'Rainbow Serpent', city: 'Lexton', country: 'Australia', genre: 'electronic', typicalMonth: 'January', durationDays: 4, ticketCost: 400, attendeeCount: 20000, monthlyRent: 1200, costIndex: 5, nomadScore: 7, nearestAirport: 'MEL', visaEase: 'e-visa' },
    { festivalName: 'Fuji Rock', city: 'Yuzawa', country: 'Japan', genre: 'multi-genre', typicalMonth: 'July', durationDays: 3, ticketCost: 300, attendeeCount: 125000, monthlyRent: 1200, costIndex: 5, nomadScore: 6, nearestAirport: 'NRT', visaEase: 'visa-free 90d' },
    { festivalName: 'ZoukOut', city: 'Singapore', country: 'Singapore', genre: 'electronic', typicalMonth: 'December', durationDays: 2, ticketCost: 150, attendeeCount: 40000, monthlyRent: 2500, costIndex: 2, nomadScore: 8, nearestAirport: 'SIN', visaEase: 'visa-free 90d' },
    { festivalName: 'Sunburn', city: 'Goa', country: 'India', genre: 'electronic', typicalMonth: 'December', durationDays: 3, ticketCost: 100, attendeeCount: 350000, monthlyRent: 400, costIndex: 10, nomadScore: 8, nearestAirport: 'GOI', visaEase: 'e-visa' },
    { festivalName: 'Outlook Festival', city: 'Pula', country: 'Croatia', genre: 'electronic', typicalMonth: 'August', durationDays: 4, ticketCost: 180, attendeeCount: 10000, monthlyRent: 900, costIndex: 7, nomadScore: 7, nearestAirport: 'PUY', visaEase: 'Schengen 90d' },
    { festivalName: 'Dimensions', city: 'Pula', country: 'Croatia', genre: 'electronic', typicalMonth: 'August', durationDays: 5, ticketCost: 200, attendeeCount: 8000, monthlyRent: 900, costIndex: 7, nomadScore: 7, nearestAirport: 'PUY', visaEase: 'Schengen 90d' },
    { festivalName: 'Oasis Festival', city: 'Marrakech', country: 'Morocco', genre: 'electronic', typicalMonth: 'September', durationDays: 3, ticketCost: 150, attendeeCount: 6000, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'RAK', visaEase: 'visa-free 90d' },
    { festivalName: 'Lost City', city: 'Tulum', country: 'Mexico', genre: 'electronic', typicalMonth: 'January', durationDays: 3, ticketCost: 200, attendeeCount: 5000, monthlyRent: 1100, costIndex: 6, nomadScore: 8, nearestAirport: 'CUN', visaEase: 'visa-free 180d' },
    { festivalName: 'Day Zero', city: 'Tulum', country: 'Mexico', genre: 'electronic', typicalMonth: 'January', durationDays: 1, ticketCost: 150, attendeeCount: 10000, monthlyRent: 1100, costIndex: 6, nomadScore: 8, nearestAirport: 'CUN', visaEase: 'visa-free 180d' },
    { festivalName: 'BPM Festival', city: 'Tamarindo', country: 'Costa Rica', genre: 'electronic', typicalMonth: 'January', durationDays: 10, ticketCost: 300, attendeeCount: 15000, monthlyRent: 1000, costIndex: 6, nomadScore: 8, nearestAirport: 'LIR', visaEase: 'visa-free 90d' },
    { festivalName: 'Mystic Valley', city: 'Chiang Dao', country: 'Thailand', genre: 'electronic', typicalMonth: 'January', durationDays: 3, ticketCost: 100, attendeeCount: 3000, monthlyRent: 450, costIndex: 10, nomadScore: 10, nearestAirport: 'CNX', visaEase: 'visa-free 60d' },
    { festivalName: 'Up the Creek', city: 'Swellendam', country: 'South Africa', genre: 'multi-genre', typicalMonth: 'February', durationDays: 3, ticketCost: 80, attendeeCount: 6000, monthlyRent: 600, costIndex: 8, nomadScore: 7, nearestAirport: 'CPT', visaEase: 'visa-free 90d' },
    { festivalName: 'Meadows in the Mountains', city: 'Rhodope', country: 'Bulgaria', genre: 'electronic', typicalMonth: 'June', durationDays: 3, ticketCost: 180, attendeeCount: 2000, monthlyRent: 550, costIndex: 9, nomadScore: 7, nearestAirport: 'SOF', visaEase: 'Schengen 90d' },
    { festivalName: 'Bushfire', city: 'Malkerns', country: 'Eswatini', genre: 'multi-genre', typicalMonth: 'May', durationDays: 3, ticketCost: 100, attendeeCount: 25000, monthlyRent: 400, costIndex: 9, nomadScore: 5, nearestAirport: 'SHO', visaEase: 'visa-free 30d' },
    { festivalName: 'We Love Green', city: 'Paris', country: 'France', genre: 'multi-genre', typicalMonth: 'June', durationDays: 2, ticketCost: 120, attendeeCount: 80000, monthlyRent: 1800, costIndex: 3, nomadScore: 7, nearestAirport: 'CDG', visaEase: 'Schengen 90d' },
    { festivalName: 'Mad Cool', city: 'Madrid', country: 'Spain', genre: 'rock', typicalMonth: 'July', durationDays: 4, ticketCost: 200, attendeeCount: 90000, monthlyRent: 1100, costIndex: 6, nomadScore: 8, nearestAirport: 'MAD', visaEase: 'Schengen 90d' },
    { festivalName: 'Electric Picnic', city: 'Stradbally', country: 'Ireland', genre: 'multi-genre', typicalMonth: 'September', durationDays: 3, ticketCost: 250, attendeeCount: 70000, monthlyRent: 1600, costIndex: 4, nomadScore: 6, nearestAirport: 'DUB', visaEase: 'visa-free 90d' },
    { festivalName: 'Clockenflap', city: 'Hong Kong', country: 'Hong Kong', genre: 'multi-genre', typicalMonth: 'December', durationDays: 3, ticketCost: 200, attendeeCount: 30000, monthlyRent: 2200, costIndex: 2, nomadScore: 7, nearestAirport: 'HKG', visaEase: 'visa-free 90d' },
  ];

  for (const fest of festivalDestinations) {
    await prisma.festival_destinations.create({ data: fest });
  }
  console.log(`✓ Seeded ${festivalDestinations.length} festival destinations`);

  // ═══════════════════════════════════════════════════════════════════
  // SKATEPARK DESTINATIONS - 33 Best Skateparks in Nomad Cities
  // ═══════════════════════════════════════════════════════════════════
  const skateparkDestinations = [
    { parkName: 'Vans Skatepark', city: 'Huntington Beach', country: 'USA', parkRating: 10, parkSize: 'mega', features: 'bowl, street, vert, flow', streetSpots: 9, monthlyRent: 2200, costIndex: 3, nomadScore: 7, nearestAirport: 'SNA', visaEase: 'ESTA/visa' },
    { parkName: 'Skate Agora', city: 'Barcelona', country: 'Spain', parkRating: 10, parkSize: 'large', features: 'street, plaza, ledges', streetSpots: 10, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { parkName: 'Burnside', city: 'Portland', country: 'USA', parkRating: 9, parkSize: 'medium', features: 'bowl, DIY', streetSpots: 8, monthlyRent: 1600, costIndex: 5, nomadScore: 8, nearestAirport: 'PDX', visaEase: 'ESTA/visa' },
    { parkName: 'Globe Bowl', city: 'Melbourne', country: 'Australia', parkRating: 9, parkSize: 'large', features: 'bowl, street, mini', streetSpots: 8, monthlyRent: 1400, costIndex: 5, nomadScore: 8, nearestAirport: 'MEL', visaEase: 'e-visa' },
    { parkName: 'SMP Skatepark', city: 'Shanghai', country: 'China', parkRating: 10, parkSize: 'mega', features: 'bowl, street, vert, flow', streetSpots: 7, monthlyRent: 1000, costIndex: 6, nomadScore: 6, nearestAirport: 'PVG', visaEase: 'visa required' },
    { parkName: 'Ruben Alcantara Skatepark', city: 'Malaga', country: 'Spain', parkRating: 9, parkSize: 'large', features: 'bowl, street, flow', streetSpots: 8, monthlyRent: 900, costIndex: 7, nomadScore: 8, nearestAirport: 'AGP', visaEase: 'Schengen 90d' },
    { parkName: 'House of Vans', city: 'London', country: 'UK', parkRating: 9, parkSize: 'medium', features: 'bowl, mini, street', streetSpots: 9, monthlyRent: 2500, costIndex: 2, nomadScore: 8, nearestAirport: 'LHR', visaEase: 'visa-free 180d' },
    { parkName: 'Bali Bowl', city: 'Canggu', country: 'Indonesia', parkRating: 8, parkSize: 'medium', features: 'bowl, mini', streetSpots: 6, monthlyRent: 600, costIndex: 9, nomadScore: 10, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { parkName: 'Tamura Skatepark', city: 'Chiang Mai', country: 'Thailand', parkRating: 7, parkSize: 'small', features: 'street, mini', streetSpots: 5, monthlyRent: 450, costIndex: 10, nomadScore: 10, nearestAirport: 'CNX', visaEase: 'visa-free 60d' },
    { parkName: 'Parque de los Reyes', city: 'Santiago', country: 'Chile', parkRating: 8, parkSize: 'large', features: 'bowl, street', streetSpots: 7, monthlyRent: 700, costIndex: 7, nomadScore: 7, nearestAirport: 'SCL', visaEase: 'visa-free 90d' },
    { parkName: 'Guadalajara Skatepark', city: 'Guadalajara', country: 'Mexico', parkRating: 8, parkSize: 'large', features: 'bowl, street, flow', streetSpots: 7, monthlyRent: 600, costIndex: 8, nomadScore: 7, nearestAirport: 'GDL', visaEase: 'visa-free 180d' },
    { parkName: 'MACBA Plaza', city: 'Barcelona', country: 'Spain', parkRating: 10, parkSize: 'small', features: 'street, ledges, gaps', streetSpots: 10, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { parkName: 'Southbank', city: 'London', country: 'UK', parkRating: 9, parkSize: 'small', features: 'street, ledges', streetSpots: 10, monthlyRent: 2500, costIndex: 2, nomadScore: 8, nearestAirport: 'LHR', visaEase: 'visa-free 180d' },
    { parkName: 'Tivoli Skatepark', city: 'Copenhagen', country: 'Denmark', parkRating: 8, parkSize: 'medium', features: 'bowl, street', streetSpots: 8, monthlyRent: 1800, costIndex: 4, nomadScore: 7, nearestAirport: 'CPH', visaEase: 'Schengen 90d' },
    { parkName: 'Pura Pura Skatepark', city: 'Bali', country: 'Indonesia', parkRating: 7, parkSize: 'small', features: 'bowl, mini', streetSpots: 5, monthlyRent: 600, costIndex: 9, nomadScore: 10, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { parkName: 'Lisbon Skatepark', city: 'Lisbon', country: 'Portugal', parkRating: 8, parkSize: 'medium', features: 'bowl, street', streetSpots: 8, monthlyRent: 1200, costIndex: 6, nomadScore: 10, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { parkName: 'Mar Bella', city: 'Barcelona', country: 'Spain', parkRating: 8, parkSize: 'medium', features: 'bowl, street', streetSpots: 9, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { parkName: 'Medellin Skatepark', city: 'Medellin', country: 'Colombia', parkRating: 7, parkSize: 'medium', features: 'street, bowl', streetSpots: 6, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'MDE', visaEase: 'visa-free 90d' },
    { parkName: 'Parque Bicentenario', city: 'Mexico City', country: 'Mexico', parkRating: 8, parkSize: 'large', features: 'bowl, street', streetSpots: 8, monthlyRent: 900, costIndex: 7, nomadScore: 10, nearestAirport: 'MEX', visaEase: 'visa-free 180d' },
    { parkName: 'Hua Hin Skatepark', city: 'Hua Hin', country: 'Thailand', parkRating: 7, parkSize: 'medium', features: 'bowl, street', streetSpots: 5, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'HHQ', visaEase: 'visa-free 60d' },
    { parkName: 'Da Nang Skatepark', city: 'Da Nang', country: 'Vietnam', parkRating: 6, parkSize: 'small', features: 'street, mini', streetSpots: 5, monthlyRent: 450, costIndex: 9, nomadScore: 9, nearestAirport: 'DAD', visaEase: 'e-visa' },
    { parkName: 'Tbilisi Skatepark', city: 'Tbilisi', country: 'Georgia', parkRating: 7, parkSize: 'medium', features: 'bowl, street', streetSpots: 6, monthlyRent: 500, costIndex: 9, nomadScore: 9, nearestAirport: 'TBS', visaEase: 'visa-free 365d' },
    { parkName: 'Florianopolis Bowl', city: 'Florianopolis', country: 'Brazil', parkRating: 8, parkSize: 'medium', features: 'bowl, street', streetSpots: 7, monthlyRent: 700, costIndex: 7, nomadScore: 7, nearestAirport: 'FLN', visaEase: 'visa-free 90d' },
    { parkName: 'Cape Town Skatepark', city: 'Cape Town', country: 'South Africa', parkRating: 7, parkSize: 'medium', features: 'bowl, street', streetSpots: 7, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'CPT', visaEase: 'visa-free 90d' },
    { parkName: 'Seoul Forest Skatepark', city: 'Seoul', country: 'South Korea', parkRating: 8, parkSize: 'medium', features: 'street, bowl', streetSpots: 7, monthlyRent: 1000, costIndex: 6, nomadScore: 7, nearestAirport: 'ICN', visaEase: 'visa-free 90d' },
    { parkName: 'Kuala Lumpur Skatepark', city: 'Kuala Lumpur', country: 'Malaysia', parkRating: 7, parkSize: 'medium', features: 'street, mini', streetSpots: 6, monthlyRent: 600, costIndex: 8, nomadScore: 8, nearestAirport: 'KUL', visaEase: 'visa-free 90d' },
    { parkName: 'Buenos Aires Skatepark', city: 'Buenos Aires', country: 'Argentina', parkRating: 7, parkSize: 'large', features: 'bowl, street', streetSpots: 7, monthlyRent: 600, costIndex: 8, nomadScore: 8, nearestAirport: 'EZE', visaEase: 'visa-free 90d' },
    { parkName: 'Taipei Skatepark', city: 'Taipei', country: 'Taiwan', parkRating: 8, parkSize: 'medium', features: 'bowl, street', streetSpots: 7, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'TPE', visaEase: 'visa-free 90d' },
    { parkName: 'Berlin Skatepark', city: 'Berlin', country: 'Germany', parkRating: 8, parkSize: 'large', features: 'bowl, street, DIY', streetSpots: 8, monthlyRent: 1300, costIndex: 5, nomadScore: 9, nearestAirport: 'BER', visaEase: 'Schengen 90d' },
    { parkName: 'Athens Skatepark', city: 'Athens', country: 'Greece', parkRating: 7, parkSize: 'medium', features: 'bowl, street', streetSpots: 7, monthlyRent: 700, costIndex: 7, nomadScore: 7, nearestAirport: 'ATH', visaEase: 'Schengen 90d' },
    { parkName: 'Oaxaca Skatepark', city: 'Oaxaca', country: 'Mexico', parkRating: 6, parkSize: 'small', features: 'street, mini', streetSpots: 6, monthlyRent: 600, costIndex: 8, nomadScore: 8, nearestAirport: 'OAX', visaEase: 'visa-free 180d' },
    { parkName: 'Split Skatepark', city: 'Split', country: 'Croatia', parkRating: 7, parkSize: 'small', features: 'street, mini', streetSpots: 6, monthlyRent: 900, costIndex: 7, nomadScore: 7, nearestAirport: 'SPU', visaEase: 'Schengen 90d' },
    { parkName: 'Phuket Skatepark', city: 'Phuket', country: 'Thailand', parkRating: 6, parkSize: 'small', features: 'street, bowl', streetSpots: 5, monthlyRent: 700, costIndex: 8, nomadScore: 8, nearestAirport: 'HKT', visaEase: 'visa-free 60d' },
  ];

  for (const park of skateparkDestinations) {
    await prisma.skatepark_destinations.create({ data: park });
  }
  console.log(`✓ Seeded ${skateparkDestinations.length} skatepark destinations`);

  // ═══════════════════════════════════════════════════════════════════
  // CONFERENCE DESTINATIONS - 33 Startup/Fintech Conference Cities
  // ═══════════════════════════════════════════════════════════════════
  const conferenceDestinations = [
    { city: 'Lisbon', country: 'Portugal', majorConferences: '["Web Summit", "Lisbon Investment Summit"]', startupScene: 10, fintechFocus: 8, vcPresence: 9, networkingScore: 10, coworkingCount: 80, monthlyRent: 1200, costIndex: 6, nomadScore: 10, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { city: 'Singapore', country: 'Singapore', majorConferences: '["Techsauce", "Singapore Fintech Festival", "Money20/20 Asia"]', startupScene: 10, fintechFocus: 10, vcPresence: 10, networkingScore: 9, coworkingCount: 100, monthlyRent: 2500, costIndex: 2, nomadScore: 8, nearestAirport: 'SIN', visaEase: 'visa-free 90d' },
    { city: 'Austin', country: 'USA', majorConferences: '["SXSW", "Austin Startup Week"]', startupScene: 10, fintechFocus: 7, vcPresence: 9, networkingScore: 10, coworkingCount: 80, monthlyRent: 1800, costIndex: 4, nomadScore: 9, nearestAirport: 'AUS', visaEase: 'ESTA/visa' },
    { city: 'Berlin', country: 'Germany', majorConferences: '["TOA", "TechCrunch Disrupt Berlin"]', startupScene: 10, fintechFocus: 9, vcPresence: 9, networkingScore: 9, coworkingCount: 100, monthlyRent: 1300, costIndex: 5, nomadScore: 9, nearestAirport: 'BER', visaEase: 'Schengen 90d' },
    { city: 'Dubai', country: 'UAE', majorConferences: '["GITEX", "Dubai Fintech Summit", "Step Conference"]', startupScene: 9, fintechFocus: 10, vcPresence: 9, networkingScore: 9, coworkingCount: 80, monthlyRent: 2000, costIndex: 3, nomadScore: 8, nearestAirport: 'DXB', visaEase: 'VOA 30d' },
    { city: 'Miami', country: 'USA', majorConferences: '["Bitcoin Miami", "eMerge Americas"]', startupScene: 9, fintechFocus: 9, vcPresence: 8, networkingScore: 9, coworkingCount: 60, monthlyRent: 2200, costIndex: 3, nomadScore: 8, nearestAirport: 'MIA', visaEase: 'ESTA/visa' },
    { city: 'Amsterdam', country: 'Netherlands', majorConferences: '["TNW Conference", "Money20/20 Europe"]', startupScene: 9, fintechFocus: 9, vcPresence: 9, networkingScore: 9, coworkingCount: 70, monthlyRent: 1800, costIndex: 4, nomadScore: 8, nearestAirport: 'AMS', visaEase: 'Schengen 90d' },
    { city: 'Mexico City', country: 'Mexico', majorConferences: '["INCmty", "Fintech Summit Latam"]', startupScene: 9, fintechFocus: 8, vcPresence: 8, networkingScore: 9, coworkingCount: 60, monthlyRent: 900, costIndex: 7, nomadScore: 10, nearestAirport: 'MEX', visaEase: 'visa-free 180d' },
    { city: 'London', country: 'UK', majorConferences: '["London Tech Week", "Fintech Week London"]', startupScene: 10, fintechFocus: 10, vcPresence: 10, networkingScore: 9, coworkingCount: 150, monthlyRent: 2500, costIndex: 2, nomadScore: 8, nearestAirport: 'LHR', visaEase: 'visa-free 180d' },
    { city: 'Barcelona', country: 'Spain', majorConferences: '["4YFN", "Smart City Expo"]', startupScene: 9, fintechFocus: 7, vcPresence: 8, networkingScore: 9, coworkingCount: 50, monthlyRent: 1400, costIndex: 5, nomadScore: 9, nearestAirport: 'BCN', visaEase: 'Schengen 90d' },
    { city: 'Tel Aviv', country: 'Israel', majorConferences: '["DLD Tel Aviv", "Calcalist Mind the Tech"]', startupScene: 10, fintechFocus: 9, vcPresence: 10, networkingScore: 10, coworkingCount: 80, monthlyRent: 1800, costIndex: 4, nomadScore: 8, nearestAirport: 'TLV', visaEase: 'visa-free 90d' },
    { city: 'Sao Paulo', country: 'Brazil', majorConferences: '["Web Summit Rio", "Fintouch"]', startupScene: 9, fintechFocus: 9, vcPresence: 8, networkingScore: 8, coworkingCount: 50, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'GRU', visaEase: 'visa-free 90d' },
    { city: 'Hong Kong', country: 'Hong Kong', majorConferences: '["RISE", "Hong Kong Fintech Week"]', startupScene: 9, fintechFocus: 10, vcPresence: 10, networkingScore: 9, coworkingCount: 80, monthlyRent: 2200, costIndex: 2, nomadScore: 7, nearestAirport: 'HKG', visaEase: 'visa-free 90d' },
    { city: 'Bangkok', country: 'Thailand', majorConferences: '["Techsauce Global Summit"]', startupScene: 8, fintechFocus: 8, vcPresence: 7, networkingScore: 8, coworkingCount: 70, monthlyRent: 600, costIndex: 9, nomadScore: 9, nearestAirport: 'BKK', visaEase: 'visa-free 60d' },
    { city: 'Tallinn', country: 'Estonia', majorConferences: '["Latitude59", "sTARTUp Day"]', startupScene: 9, fintechFocus: 9, vcPresence: 7, networkingScore: 8, coworkingCount: 20, monthlyRent: 900, costIndex: 7, nomadScore: 8, nearestAirport: 'TLL', visaEase: 'Schengen 90d' },
    { city: 'Copenhagen', country: 'Denmark', majorConferences: '["TechBBQ", "Nordic Fintech Week"]', startupScene: 8, fintechFocus: 8, vcPresence: 8, networkingScore: 8, coworkingCount: 40, monthlyRent: 1800, costIndex: 4, nomadScore: 7, nearestAirport: 'CPH', visaEase: 'Schengen 90d' },
    { city: 'Stockholm', country: 'Sweden', majorConferences: '["Slush", "Nordic Fintech Week"]', startupScene: 9, fintechFocus: 9, vcPresence: 9, networkingScore: 8, coworkingCount: 50, monthlyRent: 1600, costIndex: 4, nomadScore: 7, nearestAirport: 'ARN', visaEase: 'Schengen 90d' },
    { city: 'Lagos', country: 'Nigeria', majorConferences: '["Africa Fintech Summit", "Techpoint Build"]', startupScene: 8, fintechFocus: 9, vcPresence: 7, networkingScore: 8, coworkingCount: 30, monthlyRent: 600, costIndex: 8, nomadScore: 6, nearestAirport: 'LOS', visaEase: 'VOA' },
    { city: 'Nairobi', country: 'Kenya', majorConferences: '["Africa Tech Summit", "Moonshot"]', startupScene: 8, fintechFocus: 9, vcPresence: 7, networkingScore: 8, coworkingCount: 25, monthlyRent: 500, costIndex: 8, nomadScore: 7, nearestAirport: 'NBO', visaEase: 'e-visa' },
    { city: 'Cape Town', country: 'South Africa', majorConferences: '["AfricArena", "Africa Tech Summit"]', startupScene: 8, fintechFocus: 8, vcPresence: 7, networkingScore: 8, coworkingCount: 25, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'CPT', visaEase: 'visa-free 90d' },
    { city: 'Bogota', country: 'Colombia', majorConferences: '["Fintech Americas", "Colombia Fintech Festival"]', startupScene: 7, fintechFocus: 8, vcPresence: 6, networkingScore: 7, coworkingCount: 25, monthlyRent: 600, costIndex: 8, nomadScore: 7, nearestAirport: 'BOG', visaEase: 'visa-free 90d' },
    { city: 'Buenos Aires', country: 'Argentina', majorConferences: '["Argentina Fintech Forum"]', startupScene: 8, fintechFocus: 8, vcPresence: 7, networkingScore: 8, coworkingCount: 30, monthlyRent: 600, costIndex: 8, nomadScore: 8, nearestAirport: 'EZE', visaEase: 'visa-free 90d' },
    { city: 'Medellin', country: 'Colombia', majorConferences: '["Colombia 4.0"]', startupScene: 8, fintechFocus: 7, vcPresence: 6, networkingScore: 8, coworkingCount: 35, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'MDE', visaEase: 'visa-free 90d' },
    { city: 'Bali', country: 'Indonesia', majorConferences: '["Bali Spirit Festival Tech", "SEA founders"]', startupScene: 7, fintechFocus: 5, vcPresence: 5, networkingScore: 9, coworkingCount: 50, monthlyRent: 600, costIndex: 9, nomadScore: 10, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { city: 'Toronto', country: 'Canada', majorConferences: '["Collision", "Toronto Fintech Forum"]', startupScene: 9, fintechFocus: 9, vcPresence: 9, networkingScore: 9, coworkingCount: 80, monthlyRent: 1800, costIndex: 4, nomadScore: 8, nearestAirport: 'YYZ', visaEase: 'eTA/visa' },
    { city: 'Seoul', country: 'South Korea', majorConferences: '["beLAUNCH", "Korea Fintech Week"]', startupScene: 9, fintechFocus: 9, vcPresence: 8, networkingScore: 8, coworkingCount: 50, monthlyRent: 1000, costIndex: 6, nomadScore: 7, nearestAirport: 'ICN', visaEase: 'visa-free 90d' },
    { city: 'Tokyo', country: 'Japan', majorConferences: '["NEST", "Finsum"]', startupScene: 8, fintechFocus: 8, vcPresence: 8, networkingScore: 7, coworkingCount: 60, monthlyRent: 1500, costIndex: 5, nomadScore: 6, nearestAirport: 'NRT', visaEase: 'visa-free 90d' },
    { city: 'Mumbai', country: 'India', majorConferences: '["Global Fintech Fest", "TechSparks"]', startupScene: 9, fintechFocus: 10, vcPresence: 8, networkingScore: 8, coworkingCount: 60, monthlyRent: 600, costIndex: 9, nomadScore: 6, nearestAirport: 'BOM', visaEase: 'e-visa' },
    { city: 'Jakarta', country: 'Indonesia', majorConferences: '["Tech in Asia Jakarta", "Indonesia Fintech Show"]', startupScene: 9, fintechFocus: 9, vcPresence: 8, networkingScore: 8, coworkingCount: 50, monthlyRent: 700, costIndex: 8, nomadScore: 6, nearestAirport: 'CGK', visaEase: 'VOA 30d' },
    { city: 'Paris', country: 'France', majorConferences: '["VivaTech", "Paris Fintech Forum"]', startupScene: 9, fintechFocus: 9, vcPresence: 9, networkingScore: 9, coworkingCount: 70, monthlyRent: 1800, costIndex: 3, nomadScore: 7, nearestAirport: 'CDG', visaEase: 'Schengen 90d' },
    { city: 'Zurich', country: 'Switzerland', majorConferences: '["Swiss Fintech Fair", "Finance 2.0"]', startupScene: 8, fintechFocus: 10, vcPresence: 9, networkingScore: 8, coworkingCount: 40, monthlyRent: 2800, costIndex: 1, nomadScore: 6, nearestAirport: 'ZRH', visaEase: 'Schengen 90d' },
    { city: 'Dublin', country: 'Ireland', majorConferences: '["Dublin Tech Summit", "MoneyConf"]', startupScene: 9, fintechFocus: 9, vcPresence: 9, networkingScore: 8, coworkingCount: 50, monthlyRent: 2000, costIndex: 3, nomadScore: 7, nearestAirport: 'DUB', visaEase: 'visa-free 90d' },
    { city: 'Bangalore', country: 'India', majorConferences: '["Bengaluru Tech Summit", "India Fintech Forum"]', startupScene: 10, fintechFocus: 10, vcPresence: 9, networkingScore: 9, coworkingCount: 80, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'BLR', visaEase: 'e-visa' },
  ];

  for (const conf of conferenceDestinations) {
    await prisma.conference_destinations.create({ data: conf });
  }
  console.log(`✓ Seeded ${conferenceDestinations.length} conference destinations`);

  console.log('\n✅ Part 3 seeded successfully!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
