import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // ═══════════════════════════════════════════════════════════════════
  // SURF SPOTS - 33 Digital Nomad Surf Destinations
  // ═══════════════════════════════════════════════════════════════════
  const surfSpots = [
    { name: 'Canggu', country: 'Indonesia', region: 'Bali', waveConsistency: 8, waveType: 'beach break', waterTempLow: 79, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 25, coworkingCount: 50, monthlyRent: 600, costIndex: 9, nomadScore: 10, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Taghazout', country: 'Morocco', region: 'Agadir', waveConsistency: 8, waveType: 'point break', waterTempLow: 62, waterTempHigh: 72, bestMonths: 'Oct-Mar', wifiSpeed: 20, coworkingCount: 10, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'AGA', visaEase: 'visa-free 90d' },
    { name: 'Ericeira', country: 'Portugal', region: 'Lisbon Coast', waveConsistency: 9, waveType: 'beach break', waterTempLow: 58, waterTempHigh: 68, bestMonths: 'Sep-Apr', wifiSpeed: 100, coworkingCount: 15, monthlyRent: 1200, costIndex: 6, nomadScore: 9, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { name: 'Santa Teresa', country: 'Costa Rica', region: 'Nicoya', waveConsistency: 8, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Dec-Apr', wifiSpeed: 30, coworkingCount: 8, monthlyRent: 900, costIndex: 7, nomadScore: 8, nearestAirport: 'SJO', visaEase: 'visa-free 90d' },
    { name: 'Sayulita', country: 'Mexico', region: 'Nayarit', waveConsistency: 7, waveType: 'beach break', waterTempLow: 72, waterTempHigh: 82, bestMonths: 'Nov-Apr', wifiSpeed: 30, coworkingCount: 6, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'PVR', visaEase: 'visa-free 180d' },
    { name: 'El Tunco', country: 'El Salvador', region: 'La Libertad', waveConsistency: 9, waveType: 'point break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Mar-Oct', wifiSpeed: 20, coworkingCount: 4, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'SAL', visaEase: 'visa-free 90d' },
    { name: 'Nosara', country: 'Costa Rica', region: 'Guanacaste', waveConsistency: 8, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Dec-Apr', wifiSpeed: 25, coworkingCount: 5, monthlyRent: 1100, costIndex: 6, nomadScore: 8, nearestAirport: 'LIR', visaEase: 'visa-free 90d' },
    { name: 'Siargao', country: 'Philippines', region: 'Mindanao', waveConsistency: 8, waveType: 'reef break', waterTempLow: 80, waterTempHigh: 86, bestMonths: 'Aug-Nov', wifiSpeed: 15, coworkingCount: 6, monthlyRent: 400, costIndex: 10, nomadScore: 8, nearestAirport: 'IAO', visaEase: 'visa-free 30d' },
    { name: 'Sri Lanka South', country: 'Sri Lanka', region: 'Weligama', waveConsistency: 8, waveType: 'beach break', waterTempLow: 80, waterTempHigh: 84, bestMonths: 'Nov-Apr', wifiSpeed: 20, coworkingCount: 8, monthlyRent: 450, costIndex: 9, nomadScore: 8, nearestAirport: 'CMB', visaEase: 'e-visa' },
    { name: 'Uluwatu', country: 'Indonesia', region: 'Bali', waveConsistency: 9, waveType: 'reef break', waterTempLow: 79, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 25, coworkingCount: 20, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Hossegor', country: 'France', region: 'Landes', waveConsistency: 8, waveType: 'beach break', waterTempLow: 55, waterTempHigh: 70, bestMonths: 'Sep-Nov', wifiSpeed: 100, coworkingCount: 5, monthlyRent: 1400, costIndex: 5, nomadScore: 7, nearestAirport: 'BIQ', visaEase: 'Schengen 90d' },
    { name: 'Florianopolis', country: 'Brazil', region: 'Santa Catarina', waveConsistency: 7, waveType: 'beach break', waterTempLow: 65, waterTempHigh: 78, bestMonths: 'Apr-Sep', wifiSpeed: 50, coworkingCount: 15, monthlyRent: 700, costIndex: 7, nomadScore: 8, nearestAirport: 'FLN', visaEase: 'visa-free 90d' },
    { name: 'Las Palmas', country: 'Spain', region: 'Gran Canaria', waveConsistency: 8, waveType: 'reef break', waterTempLow: 66, waterTempHigh: 74, bestMonths: 'Oct-Mar', wifiSpeed: 100, coworkingCount: 20, monthlyRent: 900, costIndex: 7, nomadScore: 9, nearestAirport: 'LPA', visaEase: 'Schengen 90d' },
    { name: 'Peniche', country: 'Portugal', region: 'Leiria', waveConsistency: 9, waveType: 'beach break', waterTempLow: 58, waterTempHigh: 68, bestMonths: 'Sep-Apr', wifiSpeed: 80, coworkingCount: 5, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { name: 'Byron Bay', country: 'Australia', region: 'NSW', waveConsistency: 7, waveType: 'point break', waterTempLow: 66, waterTempHigh: 78, bestMonths: 'Feb-May', wifiSpeed: 50, coworkingCount: 10, monthlyRent: 2000, costIndex: 3, nomadScore: 8, nearestAirport: 'BNE', visaEase: 'e-visa' },
    { name: 'Jeffreys Bay', country: 'South Africa', region: 'Eastern Cape', waveConsistency: 8, waveType: 'point break', waterTempLow: 60, waterTempHigh: 72, bestMonths: 'Jun-Sep', wifiSpeed: 30, coworkingCount: 2, monthlyRent: 500, costIndex: 8, nomadScore: 6, nearestAirport: 'PLZ', visaEase: 'visa-free 90d' },
    { name: 'Puerto Escondido', country: 'Mexico', region: 'Oaxaca', waveConsistency: 8, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 25, coworkingCount: 8, monthlyRent: 600, costIndex: 8, nomadScore: 9, nearestAirport: 'PXM', visaEase: 'visa-free 180d' },
    { name: 'Lombok', country: 'Indonesia', region: 'Kuta', waveConsistency: 8, waveType: 'reef break', waterTempLow: 79, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 20, coworkingCount: 5, monthlyRent: 400, costIndex: 9, nomadScore: 7, nearestAirport: 'LOP', visaEase: 'VOA 30d' },
    { name: 'Fuerteventura', country: 'Spain', region: 'Canary Islands', waveConsistency: 8, waveType: 'reef break', waterTempLow: 66, waterTempHigh: 74, bestMonths: 'Oct-Mar', wifiSpeed: 80, coworkingCount: 8, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'FUE', visaEase: 'Schengen 90d' },
    { name: 'Dominical', country: 'Costa Rica', region: 'Puntarenas', waveConsistency: 7, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 20, coworkingCount: 3, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'SJO', visaEase: 'visa-free 90d' },
    { name: 'Arugam Bay', country: 'Sri Lanka', region: 'Eastern', waveConsistency: 8, waveType: 'point break', waterTempLow: 80, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 15, coworkingCount: 2, monthlyRent: 350, costIndex: 10, nomadScore: 7, nearestAirport: 'CMB', visaEase: 'e-visa' },
    { name: 'Essaouira', country: 'Morocco', region: 'Marrakech-Safi', waveConsistency: 7, waveType: 'beach break', waterTempLow: 62, waterTempHigh: 70, bestMonths: 'Oct-Mar', wifiSpeed: 25, coworkingCount: 5, monthlyRent: 450, costIndex: 9, nomadScore: 7, nearestAirport: 'ESU', visaEase: 'visa-free 90d' },
    { name: 'Montañita', country: 'Ecuador', region: 'Santa Elena', waveConsistency: 7, waveType: 'point break', waterTempLow: 72, waterTempHigh: 78, bestMonths: 'Dec-Apr', wifiSpeed: 20, coworkingCount: 3, monthlyRent: 450, costIndex: 9, nomadScore: 7, nearestAirport: 'GYE', visaEase: 'visa-free 90d' },
    { name: 'Raglan', country: 'New Zealand', region: 'Waikato', waveConsistency: 7, waveType: 'point break', waterTempLow: 56, waterTempHigh: 68, bestMonths: 'Mar-Sep', wifiSpeed: 60, coworkingCount: 2, monthlyRent: 1200, costIndex: 5, nomadScore: 6, nearestAirport: 'AKL', visaEase: 'visa-free 90d' },
    { name: 'Da Nang', country: 'Vietnam', region: 'Central', waveConsistency: 6, waveType: 'beach break', waterTempLow: 75, waterTempHigh: 84, bestMonths: 'Sep-Mar', wifiSpeed: 40, coworkingCount: 15, monthlyRent: 450, costIndex: 9, nomadScore: 9, nearestAirport: 'DAD', visaEase: 'e-visa' },
    { name: 'Biarritz', country: 'France', region: 'Nouvelle-Aquitaine', waveConsistency: 7, waveType: 'beach break', waterTempLow: 55, waterTempHigh: 70, bestMonths: 'Sep-Nov', wifiSpeed: 100, coworkingCount: 8, monthlyRent: 1500, costIndex: 4, nomadScore: 7, nearestAirport: 'BIQ', visaEase: 'Schengen 90d' },
    { name: 'San Juan del Sur', country: 'Nicaragua', region: 'Rivas', waveConsistency: 8, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Mar-Oct', wifiSpeed: 15, coworkingCount: 3, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'MGA', visaEase: 'visa-free 90d' },
    { name: 'Kuta Bali', country: 'Indonesia', region: 'Bali', waveConsistency: 7, waveType: 'beach break', waterTempLow: 79, waterTempHigh: 84, bestMonths: 'Apr-Oct', wifiSpeed: 30, coworkingCount: 30, monthlyRent: 550, costIndex: 9, nomadScore: 9, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Punta de Mita', country: 'Mexico', region: 'Nayarit', waveConsistency: 7, waveType: 'beach break', waterTempLow: 75, waterTempHigh: 85, bestMonths: 'Nov-Apr', wifiSpeed: 40, coworkingCount: 4, monthlyRent: 1000, costIndex: 6, nomadScore: 7, nearestAirport: 'PVR', visaEase: 'visa-free 180d' },
    { name: 'Bocas del Toro', country: 'Panama', region: 'Bocas', waveConsistency: 6, waveType: 'reef break', waterTempLow: 80, waterTempHigh: 84, bestMonths: 'Dec-Mar', wifiSpeed: 15, coworkingCount: 2, monthlyRent: 600, costIndex: 8, nomadScore: 7, nearestAirport: 'BOC', visaEase: 'visa-free 180d' },
    { name: 'Playa Guiones', country: 'Costa Rica', region: 'Nosara', waveConsistency: 8, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Dec-Apr', wifiSpeed: 25, coworkingCount: 4, monthlyRent: 1000, costIndex: 6, nomadScore: 8, nearestAirport: 'LIR', visaEase: 'visa-free 90d' },
    { name: 'Huanchaco', country: 'Peru', region: 'La Libertad', waveConsistency: 8, waveType: 'point break', waterTempLow: 62, waterTempHigh: 72, bestMonths: 'Mar-Dec', wifiSpeed: 20, coworkingCount: 3, monthlyRent: 400, costIndex: 9, nomadScore: 6, nearestAirport: 'TRU', visaEase: 'visa-free 183d' },
    { name: 'Tamarindo', country: 'Costa Rica', region: 'Guanacaste', waveConsistency: 7, waveType: 'beach break', waterTempLow: 78, waterTempHigh: 84, bestMonths: 'Dec-Apr', wifiSpeed: 30, coworkingCount: 6, monthlyRent: 1000, costIndex: 6, nomadScore: 8, nearestAirport: 'LIR', visaEase: 'visa-free 90d' },
  ];

  for (const spot of surfSpots) {
    await prisma.surf_spots.create({ data: spot });
  }
  console.log(`✓ Seeded ${surfSpots.length} surf spots`);

  // ═══════════════════════════════════════════════════════════════════
  // GOLF COURSES - 33 Hidden Gem Courses in Nomad-Friendly Spots
  // ═══════════════════════════════════════════════════════════════════
  const golfCourses = [
    { name: 'Nirwana Bali Golf Club', city: 'Tabanan', country: 'Indonesia', courseRating: 73.2, slopeRating: 132, greenFee: 150, sceneryRating: 10, monthlyRent: 600, costIndex: 9, nomadScore: 10, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Ria Bintan Golf Club', city: 'Bintan', country: 'Indonesia', courseRating: 72.5, slopeRating: 128, greenFee: 120, sceneryRating: 9, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'BTH', visaEase: 'VOA 30d' },
    { name: 'Fairways & Bluewater', city: 'Boracay', country: 'Philippines', courseRating: 71.8, slopeRating: 125, greenFee: 100, sceneryRating: 9, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'KLO', visaEase: 'visa-free 30d' },
    { name: 'Punta Fuego Golf', city: 'Batangas', country: 'Philippines', courseRating: 72.0, slopeRating: 130, greenFee: 80, sceneryRating: 8, monthlyRent: 400, costIndex: 9, nomadScore: 7, nearestAirport: 'MNL', visaEase: 'visa-free 30d' },
    { name: 'Bali National Golf Club', city: 'Nusa Dua', country: 'Indonesia', courseRating: 73.5, slopeRating: 135, greenFee: 175, sceneryRating: 9, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Laguna Golf Phuket', city: 'Phuket', country: 'Thailand', courseRating: 72.8, slopeRating: 128, greenFee: 150, sceneryRating: 9, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'HKT', visaEase: 'visa-free 60d' },
    { name: 'Black Mountain Golf', city: 'Hua Hin', country: 'Thailand', courseRating: 74.0, slopeRating: 140, greenFee: 100, sceneryRating: 9, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'HHQ', visaEase: 'visa-free 60d' },
    { name: 'Praia del Rey', city: 'Obidos', country: 'Portugal', courseRating: 73.0, slopeRating: 132, greenFee: 95, sceneryRating: 9, monthlyRent: 900, costIndex: 7, nomadScore: 8, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { name: 'Oitavos Dunes', city: 'Cascais', country: 'Portugal', courseRating: 74.5, slopeRating: 145, greenFee: 185, sceneryRating: 10, monthlyRent: 1200, costIndex: 6, nomadScore: 9, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { name: 'Costa Navarino', city: 'Messinia', country: 'Greece', courseRating: 73.8, slopeRating: 138, greenFee: 180, sceneryRating: 10, monthlyRent: 800, costIndex: 7, nomadScore: 7, nearestAirport: 'KLX', visaEase: 'Schengen 90d' },
    { name: 'Royal Colombo Golf', city: 'Colombo', country: 'Sri Lanka', courseRating: 70.5, slopeRating: 118, greenFee: 50, sceneryRating: 7, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'CMB', visaEase: 'e-visa' },
    { name: 'Mayakoba El Camaleon', city: 'Playa del Carmen', country: 'Mexico', courseRating: 73.2, slopeRating: 135, greenFee: 250, sceneryRating: 10, monthlyRent: 1000, costIndex: 6, nomadScore: 9, nearestAirport: 'CUN', visaEase: 'visa-free 180d' },
    { name: 'Four Seasons Punta Mita', city: 'Punta Mita', country: 'Mexico', courseRating: 74.0, slopeRating: 142, greenFee: 395, sceneryRating: 10, monthlyRent: 1000, costIndex: 6, nomadScore: 7, nearestAirport: 'PVR', visaEase: 'visa-free 180d' },
    { name: 'Vidanta Golf Vallarta', city: 'Nuevo Vallarta', country: 'Mexico', courseRating: 72.5, slopeRating: 130, greenFee: 195, sceneryRating: 9, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'PVR', visaEase: 'visa-free 180d' },
    { name: 'Tam Dao Golf', city: 'Vinh Phuc', country: 'Vietnam', courseRating: 72.0, slopeRating: 128, greenFee: 80, sceneryRating: 9, monthlyRent: 400, costIndex: 9, nomadScore: 8, nearestAirport: 'HAN', visaEase: 'e-visa' },
    { name: 'Ba Na Hills Golf', city: 'Da Nang', country: 'Vietnam', courseRating: 73.5, slopeRating: 138, greenFee: 120, sceneryRating: 10, monthlyRent: 450, costIndex: 9, nomadScore: 9, nearestAirport: 'DAD', visaEase: 'e-visa' },
    { name: 'The Bluffs Ho Tram', city: 'Ho Tram', country: 'Vietnam', courseRating: 74.2, slopeRating: 145, greenFee: 150, sceneryRating: 10, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'SGN', visaEase: 'e-visa' },
    { name: 'Coronado Golf Panama', city: 'Coronado', country: 'Panama', courseRating: 71.5, slopeRating: 122, greenFee: 80, sceneryRating: 8, monthlyRent: 700, costIndex: 8, nomadScore: 7, nearestAirport: 'PTY', visaEase: 'visa-free 180d' },
    { name: 'Club de Golf Chapultepec', city: 'Mexico City', country: 'Mexico', courseRating: 72.8, slopeRating: 132, greenFee: 200, sceneryRating: 8, monthlyRent: 900, costIndex: 7, nomadScore: 9, nearestAirport: 'MEX', visaEase: 'visa-free 180d' },
    { name: 'Aphrodite Hills', city: 'Paphos', country: 'Cyprus', courseRating: 73.0, slopeRating: 130, greenFee: 110, sceneryRating: 9, monthlyRent: 800, costIndex: 7, nomadScore: 8, nearestAirport: 'PFO', visaEase: 'Schengen 90d' },
    { name: 'Angkor Golf Resort', city: 'Siem Reap', country: 'Cambodia', courseRating: 72.2, slopeRating: 128, greenFee: 120, sceneryRating: 8, monthlyRent: 400, costIndex: 9, nomadScore: 8, nearestAirport: 'REP', visaEase: 'VOA' },
    { name: 'Red Mountain Golf', city: 'Phuket', country: 'Thailand', courseRating: 73.8, slopeRating: 140, greenFee: 170, sceneryRating: 9, monthlyRent: 700, costIndex: 8, nomadScore: 9, nearestAirport: 'HKT', visaEase: 'visa-free 60d' },
    { name: 'Banyan Golf Club', city: 'Hua Hin', country: 'Thailand', courseRating: 73.2, slopeRating: 135, greenFee: 90, sceneryRating: 8, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'HHQ', visaEase: 'visa-free 60d' },
    { name: 'Penha Longa', city: 'Sintra', country: 'Portugal', courseRating: 73.5, slopeRating: 138, greenFee: 140, sceneryRating: 10, monthlyRent: 1000, costIndex: 6, nomadScore: 8, nearestAirport: 'LIS', visaEase: 'Schengen 90d' },
    { name: 'Monte Rei', city: 'Algarve', country: 'Portugal', courseRating: 74.8, slopeRating: 148, greenFee: 250, sceneryRating: 10, monthlyRent: 1100, costIndex: 6, nomadScore: 7, nearestAirport: 'FAO', visaEase: 'Schengen 90d' },
    { name: 'Real Club Valderrama', city: 'Sotogrande', country: 'Spain', courseRating: 75.0, slopeRating: 150, greenFee: 400, sceneryRating: 9, monthlyRent: 1200, costIndex: 5, nomadScore: 7, nearestAirport: 'GIB', visaEase: 'Schengen 90d' },
    { name: 'Finca Cortesin', city: 'Malaga', country: 'Spain', courseRating: 74.5, slopeRating: 145, greenFee: 350, sceneryRating: 10, monthlyRent: 1000, costIndex: 6, nomadScore: 8, nearestAirport: 'AGP', visaEase: 'Schengen 90d' },
    { name: 'El Camaleon Riviera Maya', city: 'Tulum', country: 'Mexico', courseRating: 72.8, slopeRating: 128, greenFee: 180, sceneryRating: 9, monthlyRent: 900, costIndex: 7, nomadScore: 9, nearestAirport: 'CUN', visaEase: 'visa-free 180d' },
    { name: 'St Andrews Old Course', city: 'St Andrews', country: 'Scotland', courseRating: 72.0, slopeRating: 130, greenFee: 295, sceneryRating: 10, monthlyRent: 1500, costIndex: 4, nomadScore: 6, nearestAirport: 'EDI', visaEase: 'visa-free 180d' },
    { name: 'Palm Hills Golf', city: 'Hua Hin', country: 'Thailand', courseRating: 71.8, slopeRating: 125, greenFee: 60, sceneryRating: 8, monthlyRent: 500, costIndex: 9, nomadScore: 8, nearestAirport: 'HHQ', visaEase: 'visa-free 60d' },
    { name: 'Danang Golf Club', city: 'Da Nang', country: 'Vietnam', courseRating: 73.0, slopeRating: 132, greenFee: 100, sceneryRating: 9, monthlyRent: 450, costIndex: 9, nomadScore: 9, nearestAirport: 'DAD', visaEase: 'e-visa' },
    { name: 'New Kuta Golf', city: 'Pecatu', country: 'Indonesia', courseRating: 72.5, slopeRating: 130, greenFee: 130, sceneryRating: 10, monthlyRent: 650, costIndex: 8, nomadScore: 9, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
    { name: 'Handara Golf', city: 'Bedugul', country: 'Indonesia', courseRating: 71.5, slopeRating: 120, greenFee: 80, sceneryRating: 10, monthlyRent: 500, costIndex: 9, nomadScore: 7, nearestAirport: 'DPS', visaEase: 'VOA 30d' },
  ];

  for (const course of golfCourses) {
    await prisma.golf_courses.create({ data: course });
  }
  console.log(`✓ Seeded ${golfCourses.length} golf courses`);

  // ═══════════════════════════════════════════════════════════════════
  // NOMAD CITIES - 33 Top Cities for Entrepreneurs
  // ═══════════════════════════════════════════════════════════════════
  const nomadCities = [
    { city: 'Lisbon', country: 'Portugal', region: 'Europe', wifiSpeed: 100, coworkingCount: 80, monthlyRent: 1200, costIndex: 6, safetyRating: 9, weatherRating: 9, foodScene: 9, nightlife: 8, nomadCommunity: 10, visaEase: 'Schengen 90d', nearestAirport: 'LIS', timezone: 'WET' },
    { city: 'Bali (Canggu)', country: 'Indonesia', region: 'Asia', wifiSpeed: 30, coworkingCount: 50, monthlyRent: 600, costIndex: 9, safetyRating: 8, weatherRating: 9, foodScene: 9, nightlife: 8, nomadCommunity: 10, visaEase: 'VOA 30d', nearestAirport: 'DPS', timezone: 'WITA' },
    { city: 'Chiang Mai', country: 'Thailand', region: 'Asia', wifiSpeed: 50, coworkingCount: 40, monthlyRent: 450, costIndex: 10, safetyRating: 9, weatherRating: 7, foodScene: 10, nightlife: 7, nomadCommunity: 10, visaEase: 'visa-free 60d', nearestAirport: 'CNX', timezone: 'ICT' },
    { city: 'Mexico City', country: 'Mexico', region: 'Americas', wifiSpeed: 50, coworkingCount: 60, monthlyRent: 900, costIndex: 7, safetyRating: 6, weatherRating: 8, foodScene: 10, nightlife: 9, nomadCommunity: 10, visaEase: 'visa-free 180d', nearestAirport: 'MEX', timezone: 'CST' },
    { city: 'Medellin', country: 'Colombia', region: 'Americas', wifiSpeed: 40, coworkingCount: 35, monthlyRent: 700, costIndex: 8, safetyRating: 7, weatherRating: 10, foodScene: 8, nightlife: 9, nomadCommunity: 9, visaEase: 'visa-free 90d', nearestAirport: 'MDE', timezone: 'COT' },
    { city: 'Bangkok', country: 'Thailand', region: 'Asia', wifiSpeed: 60, coworkingCount: 70, monthlyRent: 600, costIndex: 9, safetyRating: 8, weatherRating: 6, foodScene: 10, nightlife: 9, nomadCommunity: 9, visaEase: 'visa-free 60d', nearestAirport: 'BKK', timezone: 'ICT' },
    { city: 'Barcelona', country: 'Spain', region: 'Europe', wifiSpeed: 100, coworkingCount: 50, monthlyRent: 1400, costIndex: 5, safetyRating: 7, weatherRating: 9, foodScene: 9, nightlife: 10, nomadCommunity: 9, visaEase: 'Schengen 90d', nearestAirport: 'BCN', timezone: 'CET' },
    { city: 'Playa del Carmen', country: 'Mexico', region: 'Americas', wifiSpeed: 40, coworkingCount: 25, monthlyRent: 1000, costIndex: 7, safetyRating: 7, weatherRating: 9, foodScene: 8, nightlife: 8, nomadCommunity: 9, visaEase: 'visa-free 180d', nearestAirport: 'CUN', timezone: 'EST' },
    { city: 'Ho Chi Minh City', country: 'Vietnam', region: 'Asia', wifiSpeed: 45, coworkingCount: 40, monthlyRent: 500, costIndex: 9, safetyRating: 8, weatherRating: 6, foodScene: 10, nightlife: 8, nomadCommunity: 8, visaEase: 'e-visa', nearestAirport: 'SGN', timezone: 'ICT' },
    { city: 'Tbilisi', country: 'Georgia', region: 'Europe', wifiSpeed: 40, coworkingCount: 20, monthlyRent: 500, costIndex: 9, safetyRating: 9, weatherRating: 7, foodScene: 9, nightlife: 8, nomadCommunity: 9, visaEase: 'visa-free 365d', nearestAirport: 'TBS', timezone: 'GET' },
    { city: 'Buenos Aires', country: 'Argentina', region: 'Americas', wifiSpeed: 35, coworkingCount: 30, monthlyRent: 600, costIndex: 8, safetyRating: 6, weatherRating: 8, foodScene: 9, nightlife: 10, nomadCommunity: 8, visaEase: 'visa-free 90d', nearestAirport: 'EZE', timezone: 'ART' },
    { city: 'Da Nang', country: 'Vietnam', region: 'Asia', wifiSpeed: 40, coworkingCount: 15, monthlyRent: 450, costIndex: 9, safetyRating: 9, weatherRating: 8, foodScene: 9, nightlife: 6, nomadCommunity: 8, visaEase: 'e-visa', nearestAirport: 'DAD', timezone: 'ICT' },
    { city: 'Cape Town', country: 'South Africa', region: 'Africa', wifiSpeed: 35, coworkingCount: 25, monthlyRent: 800, costIndex: 7, safetyRating: 5, weatherRating: 9, foodScene: 9, nightlife: 8, nomadCommunity: 8, visaEase: 'visa-free 90d', nearestAirport: 'CPT', timezone: 'SAST' },
    { city: 'Split', country: 'Croatia', region: 'Europe', wifiSpeed: 60, coworkingCount: 10, monthlyRent: 900, costIndex: 7, safetyRating: 9, weatherRating: 9, foodScene: 8, nightlife: 7, nomadCommunity: 7, visaEase: 'Schengen 90d', nearestAirport: 'SPU', timezone: 'CET' },
    { city: 'Las Palmas', country: 'Spain', region: 'Europe', wifiSpeed: 100, coworkingCount: 20, monthlyRent: 900, costIndex: 7, safetyRating: 9, weatherRating: 10, foodScene: 8, nightlife: 7, nomadCommunity: 9, visaEase: 'Schengen 90d', nearestAirport: 'LPA', timezone: 'WET' },
    { city: 'Belgrade', country: 'Serbia', region: 'Europe', wifiSpeed: 50, coworkingCount: 15, monthlyRent: 600, costIndex: 8, safetyRating: 8, weatherRating: 7, foodScene: 8, nightlife: 9, nomadCommunity: 7, visaEase: 'visa-free 90d', nearestAirport: 'BEG', timezone: 'CET' },
    { city: 'Kuala Lumpur', country: 'Malaysia', region: 'Asia', wifiSpeed: 50, coworkingCount: 35, monthlyRent: 600, costIndex: 8, safetyRating: 8, weatherRating: 6, foodScene: 10, nightlife: 7, nomadCommunity: 8, visaEase: 'visa-free 90d', nearestAirport: 'KUL', timezone: 'MYT' },
    { city: 'Tulum', country: 'Mexico', region: 'Americas', wifiSpeed: 30, coworkingCount: 15, monthlyRent: 1100, costIndex: 6, safetyRating: 7, weatherRating: 9, foodScene: 8, nightlife: 8, nomadCommunity: 8, visaEase: 'visa-free 180d', nearestAirport: 'CUN', timezone: 'EST' },
    { city: 'Tallinn', country: 'Estonia', region: 'Europe', wifiSpeed: 100, coworkingCount: 20, monthlyRent: 900, costIndex: 7, safetyRating: 10, weatherRating: 5, foodScene: 7, nightlife: 7, nomadCommunity: 8, visaEase: 'Schengen 90d', nearestAirport: 'TLL', timezone: 'EET' },
    { city: 'Austin', country: 'USA', region: 'Americas', wifiSpeed: 100, coworkingCount: 80, monthlyRent: 1800, costIndex: 4, safetyRating: 8, weatherRating: 7, foodScene: 9, nightlife: 9, nomadCommunity: 9, visaEase: 'ESTA/visa', nearestAirport: 'AUS', timezone: 'CST' },
    { city: 'Bogota', country: 'Colombia', region: 'Americas', wifiSpeed: 40, coworkingCount: 25, monthlyRent: 600, costIndex: 8, safetyRating: 6, weatherRating: 7, foodScene: 8, nightlife: 8, nomadCommunity: 7, visaEase: 'visa-free 90d', nearestAirport: 'BOG', timezone: 'COT' },
    { city: 'Porto', country: 'Portugal', region: 'Europe', wifiSpeed: 80, coworkingCount: 25, monthlyRent: 900, costIndex: 7, safetyRating: 9, weatherRating: 8, foodScene: 9, nightlife: 7, nomadCommunity: 8, visaEase: 'Schengen 90d', nearestAirport: 'OPO', timezone: 'WET' },
    { city: 'Taipei', country: 'Taiwan', region: 'Asia', wifiSpeed: 80, coworkingCount: 30, monthlyRent: 800, costIndex: 7, safetyRating: 10, weatherRating: 7, foodScene: 10, nightlife: 7, nomadCommunity: 7, visaEase: 'visa-free 90d', nearestAirport: 'TPE', timezone: 'CST' },
    { city: 'Berlin', country: 'Germany', region: 'Europe', wifiSpeed: 80, coworkingCount: 100, monthlyRent: 1300, costIndex: 5, safetyRating: 8, weatherRating: 6, foodScene: 8, nightlife: 10, nomadCommunity: 9, visaEase: 'Schengen 90d', nearestAirport: 'BER', timezone: 'CET' },
    { city: 'Seoul', country: 'South Korea', region: 'Asia', wifiSpeed: 150, coworkingCount: 50, monthlyRent: 1000, costIndex: 6, safetyRating: 10, weatherRating: 7, foodScene: 10, nightlife: 9, nomadCommunity: 7, visaEase: 'visa-free 90d', nearestAirport: 'ICN', timezone: 'KST' },
    { city: 'Sofia', country: 'Bulgaria', region: 'Europe', wifiSpeed: 60, coworkingCount: 15, monthlyRent: 550, costIndex: 9, safetyRating: 8, weatherRating: 7, foodScene: 7, nightlife: 7, nomadCommunity: 7, visaEase: 'Schengen 90d', nearestAirport: 'SOF', timezone: 'EET' },
    { city: 'Florianopolis', country: 'Brazil', region: 'Americas', wifiSpeed: 50, coworkingCount: 15, monthlyRent: 700, costIndex: 7, safetyRating: 7, weatherRating: 8, foodScene: 8, nightlife: 8, nomadCommunity: 7, visaEase: 'visa-free 90d', nearestAirport: 'FLN', timezone: 'BRT' },
    { city: 'Ericeira', country: 'Portugal', region: 'Europe', wifiSpeed: 80, coworkingCount: 10, monthlyRent: 1000, costIndex: 6, safetyRating: 9, weatherRating: 8, foodScene: 8, nightlife: 6, nomadCommunity: 8, visaEase: 'Schengen 90d', nearestAirport: 'LIS', timezone: 'WET' },
    { city: 'Phuket', country: 'Thailand', region: 'Asia', wifiSpeed: 45, coworkingCount: 20, monthlyRent: 700, costIndex: 8, safetyRating: 8, weatherRating: 8, foodScene: 9, nightlife: 8, nomadCommunity: 8, visaEase: 'visa-free 60d', nearestAirport: 'HKT', timezone: 'ICT' },
    { city: 'Oaxaca', country: 'Mexico', region: 'Americas', wifiSpeed: 30, coworkingCount: 10, monthlyRent: 600, costIndex: 8, safetyRating: 7, weatherRating: 9, foodScene: 10, nightlife: 7, nomadCommunity: 8, visaEase: 'visa-free 180d', nearestAirport: 'OAX', timezone: 'CST' },
    { city: 'Hanoi', country: 'Vietnam', region: 'Asia', wifiSpeed: 40, coworkingCount: 25, monthlyRent: 450, costIndex: 9, safetyRating: 8, weatherRating: 6, foodScene: 10, nightlife: 7, nomadCommunity: 7, visaEase: 'e-visa', nearestAirport: 'HAN', timezone: 'ICT' },
    { city: 'Singapore', country: 'Singapore', region: 'Asia', wifiSpeed: 200, coworkingCount: 100, monthlyRent: 2500, costIndex: 2, safetyRating: 10, weatherRating: 6, foodScene: 10, nightlife: 8, nomadCommunity: 8, visaEase: 'visa-free 90d', nearestAirport: 'SIN', timezone: 'SGT' },
    { city: 'Dubai', country: 'UAE', region: 'Middle East', wifiSpeed: 100, coworkingCount: 80, monthlyRent: 2000, costIndex: 3, safetyRating: 10, weatherRating: 5, foodScene: 9, nightlife: 7, nomadCommunity: 8, visaEase: 'VOA 30d', nearestAirport: 'DXB', timezone: 'GST' },
  ];

  for (const city of nomadCities) {
    await prisma.nomad_cities.create({ data: city });
  }
  console.log(`✓ Seeded ${nomadCities.length} nomad cities`);

  console.log('\n✅ All destination data seeded successfully!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
