/**
 * SHOWROOM-TRUTH-FIX: the Trade showcase's demo rows, GENERATED by the real
 * scoring engine — not hand-typed.
 *
 * The SHOWROOM-TRUTH-AUDIT found the old hand-typed NO-TRADE row contradicted
 * the engine three ways (miscounted its own gates; showed NO TRADE where the
 * engine gives a 20% marginal position; showed a null composite that is
 * impossible with four scored gates). The fix: the demo DECLARES three fully
 * synthetic inputs (fictional tickers, invented-but-plausible market data,
 * one shared macro snapshot exactly like a real scan) and calls the REAL pure
 * scorer `scoreAll` (src/lib/convergence/composite.ts:118) on them at module
 * load. Every score, the composite, the gate-count caption
 * (`composite.convergence_gate` — the engine's own string, verbatim), the
 * position size, the strategy suggestion, and the survival-brake state below
 * are ENGINE OUTPUT. The demo cannot drift from the engine again: if the
 * engine's rules change, these rows change with it at the next build.
 *
 * TRIPWIRE HELD: this file only CALLS the engine — no engine logic changed.
 * The inputs are static fiction (zero fetches, zero paid calls, nothing
 * personal — the SHOW discipline of TabShowcases.tsx); only the SCORING is
 * real. scoreAll is pure (no I/O — see composite.ts imports), so calling it
 * client-side is side-effect-free; the cost is bundling the scorer (~the same
 * page already ships the full ConvergenceIntelligence surface).
 */

import { scoreAll } from '@/lib/convergence/composite';
import type { ConvergenceInput, FredMacroData, TTScannerData, CandleData } from '@/lib/convergence/types';

// ── declared synthetic inputs ────────────────────────────────────────────────

/**
 * One macro snapshot shared by all three rows, like a real scan. Declared
 * values: calm contango (VIX 15.2 / VIX3M 17.1 → ratio 0.89 < 1; VVIX 92 <
 * 110) so the survival brake reads OFF — and that state is rendered from the
 * engine's own declaration, not asserted here.
 */
const DEMO_MACRO: FredMacroData = {
  vix: 15.2,
  treasury10y: 4.1,
  fedFunds: 4.375,
  unemployment: 4.1,
  cpi: 320.3,
  gdp: 28000,
  consumerConfidence: 104,
  nonfarmPayrolls: 158000,
  cpiMom: 0.2,
  yieldCurveSpread: 0.45,
  breakeven5y: 2.3,
  hySpread: 3.1,
  nfci: -0.5,
  initialClaims: 220000,
  initialClaimsDate: '2026-07-02',
  nfciDate: '2026-07-03',
  vxvShortTerm: 17.1,
  vvix: 92,
  // Fed net-liquidity + extra credit/rate series: declared ABSENT (null) — the
  // engine excludes and renormalizes, exactly as on a real run without them.
  fedBalanceSheet: null,
  treasuryGeneralAccount: null,
  overnightReverseRepo: null,
  bbbSpread: null,
  t10y3m: null,
  dollarIndex: null,
};

/**
 * Deterministic synthetic daily candles (no randomness — the same rows render
 * on every build). A fixed repeating daily-return pattern scaled per ticker:
 * `scale` ≈ how volatile the fictional stock is.
 */
function demoCandles(startPrice: number, scale: number, days = 130): CandleData[] {
  // ~1% average absolute daily move at scale 1 — an ordinary large-cap.
  const pattern = [0.8, -0.6, 1.2, -0.9, 0.4, -1.1, 0.7, 1.5, -0.5, -1.3, 0.9, 0.3];
  const candles: CandleData[] = [];
  let close = startPrice;
  const dayMs = 24 * 60 * 60 * 1000;
  const start = Date.UTC(2026, 0, 5); // fixed, declared demo epoch
  for (let i = 0; i < days; i++) {
    const retPct = pattern[i % pattern.length] * scale;
    const open = close;
    close = Math.round(open * (1 + retPct / 100) * 100) / 100;
    const hi = Math.max(open, close);
    const lo = Math.min(open, close);
    const t = start + i * dayMs;
    candles.push({
      time: Math.floor(t / 1000),
      date: new Date(t).toISOString().slice(0, 10),
      open,
      high: Math.round(hi * 1.004 * 100) / 100,
      low: Math.round(lo * 0.996 * 100) / 100,
      close,
      volume: 1_000_000 + (i % 7) * 50_000,
    });
  }
  return candles;
}

function demoScanner(overrides: Partial<TTScannerData> & { symbol: string }): TTScannerData {
  return {
    ivRank: null,
    ivPercentile: null,
    impliedVolatility: null,
    liquidityRating: null,
    earningsDate: null,
    daysTillEarnings: null,
    hv30: null,
    hv60: null,
    hv90: null,
    iv30: null,
    ivHvSpread: null,
    beta: null,
    corrSpy: null,
    marketCap: null,
    sector: null,
    industry: null,
    peRatio: null,
    eps: null,
    dividendYield: null,
    lendability: null,
    borrowRate: null,
    earningsActualEps: null,
    earningsEstimate: null,
    earningsTimeOfDay: null,
    termStructure: [],
    ...overrides,
  };
}

/** Fields every row leaves absent (feeds a real scan may also lack) — the
 *  engine EXCLUDES them and renormalizes; the N/M declarations render that. */
const ABSENT = {
  finnhubEstimates: null,
  annualFinancials: null,
  quarterlyFinancials: null,
  optionsFlow: null,
  newsSentiment: null,
  finnhubNewsSentiment: null,
  finnhubEarningsQuality: null,
  finnhubInstitutionalOwnership: null,
  finnhubRevenueBreakdown: null,
  secFilingData: null,
  secForm4Data: null,
  finnhubFundOwnership: null,
  edgar8kScan: null,
  crossAssetCorrelations: null,
} as const;

// ACME — the fictional vol-rich, fundamentally strong candidate.
const ACME: ConvergenceInput = {
  symbol: 'ACME',
  ttScanner: demoScanner({
    symbol: 'ACME',
    ivRank: 78, ivPercentile: 82, impliedVolatility: 42, liquidityRating: 4,
    earningsDate: null, daysTillEarnings: 38,
    hv30: 28, hv60: 30, hv90: 31, iv30: 41, ivHvSpread: 13,
    beta: 1.1, corrSpy: 0.65, marketCap: 48_000_000_000,
    sector: 'Technology', industry: 'Software',
    peRatio: 24, eps: 5.2, dividendYield: 0.8,
    lendability: 'Easy To Borrow', borrowRate: 0.3,
    earningsActualEps: 1.32, earningsEstimate: 1.21, earningsTimeOfDay: 'AMC',
    termStructure: [
      { date: '2026-08-21', iv: 43 },
      { date: '2026-09-18', iv: 41 },
      { date: '2026-10-16', iv: 39 },
    ],
  }),
  candles: demoCandles(180, 1.0),
  finnhubFundamentals: {
    fieldCount: 19,
    metric: {
      roeTTM: 28, roaTTM: 12, grossMarginTTM: 62, operatingMarginTTM: 25,
      revenueGrowthTTMYoy: 18, epsGrowthTTMYoy: 22, currentRatioQuarterly: 2.1,
      evEbitdaTTM: 14, evEbitdaAnnual: 15, peNormalizedAnnual: 23,
      psTTM: 6.5, psAnnual: 6.8, freeCashFlowPerShareTTM: 4.8,
      netIncomePerShareTTM: 5.1, assetTurnoverTTM: 0.7,
      marketCapitalization: 48_000, shareOutstanding: 920,
      beta: 1.1, dividendGrowthRate5Y: 6,
    },
  },
  finnhubRecommendations: [
    { strongBuy: 9, buy: 18, hold: 6, sell: 1, strongSell: 0, period: '2026-06-01' },
    { strongBuy: 8, buy: 16, hold: 8, sell: 1, strongSell: 0, period: '2026-05-01' },
    { strongBuy: 7, buy: 15, hold: 9, sell: 2, strongSell: 0, period: '2026-04-01' },
  ],
  finnhubInsiderSentiment: [
    { symbol: 'ACME', year: 2026, month: 5, change: 120_000, mspr: 34 },
    { symbol: 'ACME', year: 2026, month: 6, change: 80_000, mspr: 28 },
  ],
  finnhubEarnings: [
    { actual: 1.32, estimate: 1.21, period: '2026-03-31', surprise: 0.11, surprisePercent: 9.1, symbol: 'ACME' },
    { actual: 1.18, estimate: 1.12, period: '2025-12-31', surprise: 0.06, surprisePercent: 5.4, symbol: 'ACME' },
    { actual: 1.09, estimate: 1.1, period: '2025-09-30', surprise: -0.01, surprisePercent: -0.9, symbol: 'ACME' },
    { actual: 1.02, estimate: 0.98, period: '2025-06-30', surprise: 0.04, surprisePercent: 4.1, symbol: 'ACME' },
  ],
  fredMacro: DEMO_MACRO,
  ...ABSENT,
};

// GLOBEX — the fictional middling candidate: some vol edge, mixed quality.
const GLOBEX: ConvergenceInput = {
  symbol: 'GLOBEX',
  ttScanner: demoScanner({
    symbol: 'GLOBEX',
    ivRank: 52, ivPercentile: 55, impliedVolatility: 31, liquidityRating: 3,
    earningsDate: null, daysTillEarnings: 52,
    hv30: 26, hv60: 27, hv90: 27, iv30: 30, ivHvSpread: 4,
    beta: 0.9, corrSpy: 0.7, marketCap: 22_000_000_000,
    sector: 'Industrials', industry: 'Machinery',
    peRatio: 17, eps: 3.4, dividendYield: 2.1,
    lendability: 'Easy To Borrow', borrowRate: 0.3,
    earningsActualEps: 0.84, earningsEstimate: 0.86, earningsTimeOfDay: 'BMO',
    termStructure: [
      { date: '2026-08-21', iv: 31 },
      { date: '2026-09-18', iv: 30.5 },
    ],
  }),
  candles: demoCandles(95, 0.9),
  finnhubFundamentals: {
    fieldCount: 19,
    metric: {
      roeTTM: 11, roaTTM: 5, grossMarginTTM: 31, operatingMarginTTM: 9,
      revenueGrowthTTMYoy: 4, epsGrowthTTMYoy: 2, currentRatioQuarterly: 1.4,
      evEbitdaTTM: 10, evEbitdaAnnual: 10.5, peNormalizedAnnual: 16,
      psTTM: 1.4, psAnnual: 1.5, freeCashFlowPerShareTTM: 2.1,
      netIncomePerShareTTM: 3.2, assetTurnoverTTM: 0.9,
      marketCapitalization: 22_000, shareOutstanding: 640,
      beta: 0.9, dividendGrowthRate5Y: 3,
    },
  },
  finnhubRecommendations: [
    { strongBuy: 3, buy: 8, hold: 14, sell: 3, strongSell: 1, period: '2026-06-01' },
    { strongBuy: 3, buy: 9, hold: 13, sell: 3, strongSell: 1, period: '2026-05-01' },
    { strongBuy: 4, buy: 9, hold: 12, sell: 3, strongSell: 1, period: '2026-04-01' },
  ],
  finnhubInsiderSentiment: [
    { symbol: 'GLOBEX', year: 2026, month: 5, change: -10_000, mspr: -4 },
    { symbol: 'GLOBEX', year: 2026, month: 6, change: 15_000, mspr: 6 },
  ],
  finnhubEarnings: [
    { actual: 0.84, estimate: 0.86, period: '2026-03-31', surprise: -0.02, surprisePercent: -2.3, symbol: 'GLOBEX' },
    { actual: 0.9, estimate: 0.88, period: '2025-12-31', surprise: 0.02, surprisePercent: 2.3, symbol: 'GLOBEX' },
    { actual: 0.86, estimate: 0.85, period: '2025-09-30', surprise: 0.01, surprisePercent: 1.2, symbol: 'GLOBEX' },
  ],
  fredMacro: DEMO_MACRO,
  ...ABSENT,
};

// INITECH — the fictional weak candidate: cheap options (no vol edge), soft
// fundamentals, deteriorating analyst/insider signals. Declared to show what
// the engine does when convergence fails — whatever it computes is rendered.
const INITECH: ConvergenceInput = {
  symbol: 'INITECH',
  ttScanner: demoScanner({
    symbol: 'INITECH',
    ivRank: 9, ivPercentile: 12, impliedVolatility: 22, liquidityRating: 2,
    earningsDate: null, daysTillEarnings: 12,
    hv30: 29, hv60: 27, hv90: 26, iv30: 22, ivHvSpread: -7,
    beta: 1.3, corrSpy: 0.5, marketCap: 3_000_000_000,
    sector: 'Technology', industry: 'IT Services',
    peRatio: 41, eps: 0.6, dividendYield: 0,
    lendability: 'Hard To Borrow', borrowRate: 4.2,
    earningsActualEps: 0.09, earningsEstimate: 0.16, earningsTimeOfDay: 'AMC',
    termStructure: [
      { date: '2026-08-21', iv: 22 },
      { date: '2026-09-18', iv: 23 },
    ],
  }),
  candles: demoCandles(28, 1.4),
  finnhubFundamentals: {
    fieldCount: 19,
    metric: {
      roeTTM: 2, roaTTM: 0.8, grossMarginTTM: 18, operatingMarginTTM: 2,
      revenueGrowthTTMYoy: -6, epsGrowthTTMYoy: -35, currentRatioQuarterly: 0.8,
      evEbitdaTTM: 22, evEbitdaAnnual: 24, peNormalizedAnnual: 44,
      psTTM: 0.9, psAnnual: 1.0, freeCashFlowPerShareTTM: -0.4,
      netIncomePerShareTTM: 0.5, assetTurnoverTTM: 0.5,
      marketCapitalization: 3_000, shareOutstanding: 210,
      beta: 1.3, dividendGrowthRate5Y: 0,
    },
  },
  finnhubRecommendations: [
    { strongBuy: 0, buy: 2, hold: 9, sell: 6, strongSell: 3, period: '2026-06-01' },
    { strongBuy: 1, buy: 3, hold: 9, sell: 5, strongSell: 2, period: '2026-05-01' },
    { strongBuy: 1, buy: 4, hold: 9, sell: 4, strongSell: 2, period: '2026-04-01' },
  ],
  finnhubInsiderSentiment: [
    { symbol: 'INITECH', year: 2026, month: 5, change: -240_000, mspr: -41 },
    { symbol: 'INITECH', year: 2026, month: 6, change: -95_000, mspr: -28 },
  ],
  finnhubEarnings: [
    { actual: 0.09, estimate: 0.16, period: '2026-03-31', surprise: -0.07, surprisePercent: -43.8, symbol: 'INITECH' },
    { actual: 0.14, estimate: 0.18, period: '2025-12-31', surprise: -0.04, surprisePercent: -22.2, symbol: 'INITECH' },
    { actual: 0.2, estimate: 0.19, period: '2025-09-30', surprise: 0.01, surprisePercent: 5.3, symbol: 'INITECH' },
  ],
  fredMacro: DEMO_MACRO,
  ...ABSENT,
};

// ── engine output → plain rows ───────────────────────────────────────────────

export interface TradeShowcaseRow {
  ticker: string;
  volEdge: number | null;
  quality: number | null;
  regime: number | null;
  infoEdge: number | null;
  composite: number | null;
  /** The engine's own convergence-gate string, verbatim (composite.ts:159-170). */
  gate: string;
  positionSizePct: number;
  /** Engine strategy suggestion — rendered only when the engine sizes > 0. */
  strategy: string;
  suggestedDte: number;
}

const r1 = (v: number | null): number | null => (v == null ? null : Math.round(v * 10) / 10);

function toRow(input: ConvergenceInput): TradeShowcaseRow {
  const res = scoreAll(input);
  return {
    ticker: input.symbol,
    volEdge: r1(res.vol_edge.score),
    quality: r1(res.quality.score),
    regime: r1(res.regime.score),
    infoEdge: r1(res.info_edge.score),
    composite: r1(res.composite.score),
    gate: res.composite.convergence_gate,
    positionSizePct: res.composite.position_size_pct,
    strategy: res.strategy_suggestion.suggested_strategy,
    suggestedDte: res.strategy_suggestion.suggested_dte,
  };
}

/** The three demo rows — computed by the real engine on the declared inputs. */
export const TRADE_SHOWCASE_ROWS: TradeShowcaseRow[] = [ACME, GLOBEX, INITECH].map(toRow);

/** The engine's survival-brake declaration for the shared demo macro (all rows
 *  see the same market state, like a real scan) — rendered verbatim. */
export const TRADE_SHOWCASE_BRAKE: { state: 'OFF' | 'ON' | 'UNVERIFIED'; declaration: string } =
  scoreAll(ACME).composite.regime_brake;
